const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
    SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUl3cXY2dXFsZkhWZUs3MEpUbHZSd1I5R09lRG0wUzh2aGx1Z2F1REVGYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieWZSUU5vUk93d0pnWnB2VW93b3FQOFFEQ0I3azl6Zk12ZFdHcjNKUTMxcz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ3UGZ2MlIrSU5ROWZHRGxIWGJJZEc0RUlQNDhJc2xyOSs4c1hFdllmZ0VRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5bmRVOWU5UmhQRjVpN0srLzl5WTNweFpXYTRxWFJhL3p3eUlBTVNiUXpnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImNPdTlRSldZcmdUVFdqQTJ4d0JBYUVsNVkxd0JxZllWQjVrRWZnRlFKbmc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImcvekJFVDNwVENDTHJEKzAyYTZ1SzJsT0xTemZ1UDBNQzVZbW9zQ3VHU009In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUJsMWFPUkhpN3FQRXNWOGoyR2NOY29RUFpHUkZhTlVsNmM0d3o4M3IyWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicGVmRDg3RGJkQis2Y2JFMjg5ZmxWMW1kTHZkVGI2c0c5eDNOM2RtWXNXdz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkIzQlVhZkxPY3VsYXNsRnRqK3hXQ0dxNmRKZXExaDA3elpDZ2k2TUIxTVJuUHcyVDcyV1dkdVlUZi9hamRmbkNMNVk3ZGpDZXoyUW1BVTIxOCtGdmdnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQ1LCJhZHZTZWNyZXRLZXkiOiJBNFlBQTYwZTZURlV5dDlPNGJWcm1nZnVrQitOcEhnWUZyM0VsSk1WVjlFPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJQb1pOTHhHblJudTlmRkZrY0h3a0R3IiwicGhvbmVJZCI6ImJhM2JkYzE4LTIzMTYtNGMwNy1iOTA5LWY1NWI2ZjM0N2M4MCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIxUHdxdTFGNERCWU5RRm5BVTdUMWZMQmJzUGM9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVVZQSnVZWE9NUzF2amVUYWMzUkFMeXJCVzk4PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkFWTllHWENZIiwibWUiOnsiaWQiOiIyNjM3ODAxNTc1MDA6MjlAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ092VXJJY0dFSUxvZ3J3R0dBSWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Im9nRGlTUU90TkVCbU9rendNbFgrYTVveVJkekpLeXRKQkdXbjFYcFFQRVk9IiwiYWNjb3VudFNpZ25hdHVyZSI6InMvVjBXVnhQNVFveUMxREdtK2llZ09VSHBja2ZPdExMZGo4NlZUQ1ZWbWVwU1hIZllHamxPcll1MEZWWVZLMW5UN21Vem9OUk1xbCtlbWtScjRzMkJnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJQV0JwRE5ZSXVxczdaNURGRm1xeHlMYjhDNkhFdFZIaHVlUDcrZXRUVmhoRnp6N0huSlZOaGFKUjBUaXV5anR4TXE5TlhjMGRyOVBpVmpQbm1QSERpUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI2Mzc4MDE1NzUwMDoyOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJhSUE0a2tEclRSQVpqcE04REpWL211YU1rWGN5U3NyU1FSbHA5VjZVRHhHIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM2NDg3OTUxLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUUrRCJ9",
    CAPTION: process.env.CAPTION || "code by yessertech ",
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
    AUTO_REPLY_STATUS: process.env.AUTO_REPLY_STATUS || "true",
    READ_MESSAGE: process.env.READ_MESSAGE || "true", // Added auto-read configuration
    MODE: process.env.MODE || "public",
    AUTO_VOICE: process.env.AUTO_VOICE || "true",
    AUTO_STICKER: process.env.AUTO_STICKER || "false",
    AUTO_REPLY: process.env.AUTO_REPLY || "false",
    ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/3kdkf6.jpg",
    ALIVE_MSG: process.env.ALIVE_MSG || "HII DEAR IM ONLINE I'M YESSER-MD WHATSAPP BOT 👍🤠",
    ANTI_LINK: process.env.ANTI_LINK || "true",
    ANTI_BAD: process.env.ANTI_BAD || "true",
    PREFIX: process.env.PREFIX || ".",
    FAKE_RECORDING: process.env.FAKE_RECORDING || "true",
    FAKE_TYPING: process.env.FAKE_TYPING || "false",
    ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
    CURRENT_STATUS: process.env.CURRENT_STATUS || "true",
    AUTO_REACT: process.env.AUTO_REACT || "false",
    HEART_REACT: process.env.HEART_REACT || "true",
    OWNER_REACT: process.env.OWNER_REACT || "true",
    BOT_NAME: process.env.BOT_NAME || "yessertech",
    STATUS_REPLY: process.env.STATUS_REPLY || "false",
    OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
};
